---
title: "Lab 5"
author: "Max Ward"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
milk <- read.csv('state_milk_production.csv')
milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)
```

```{r}
milk1998 <- milk %>%
  filter(year == 1998)
ggplot(data = milk1998, aes(x = milk_million)) +
  geom_density() + 
  ggtitle('Distribution estimate of milk produced in 1998 by state')
```

```{r}
Individual_Part2 <- milk %>%
  filter(year == 1998) %>%
  summarize(average = mean(milk_million),middle = median(milk_million),
            max(milk_million),min(milk_million))
```

```{r}
statemilk <- milk1998 %>%
group_by(state)%>%
summarise(medianproduction = median(milk_million, na.rm = TRUE))
statemilk
```

```{r}
statemilk2 <- milk1998 %>%
group_by(state)%>%
summarise(avgproduction = mean(milk_million, na.rm = TRUE))
statemilk2
```

```{r}
MaxTeam <- milk %>%
  filter(year == 2017)%>%
  group_by(state)%>%
  arrange(desc(milk_million))
MaxTeam
```
As we can see from the data in 2017 the top five states in milk production were Califorina, Wisconsin, New York, Idaho and Texas.
```{r}
MaxTeam <- milk %>%
  filter(year == 2017)%>%
  group_by(state)%>%
  arrange(desc(-milk_million))
MaxTeam
```
As we can see for this data is that in 2017 the lowest five states in milk production were Alaska, Rhode Island, Hawaii, Arkansas and Alabama. 


